# -*- coding: utf-8 -*-
"""Calculos_Topografia1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZVYmZbga5MwIOOYtYJ22SWLbd0p-0YfD
"""

import math

# ==========================================
# FUNÇÕES CORE (LÓGICA MATEMÁTICA)
# ==========================================

def parse_angulo(angulo_str):
    """
    Recebe uma string 'G M S' e converte para graus decimais.
    Trata espaços extras e valida a quantidade de entradas.
    """
    partes = angulo_str.strip().split()
    if len(partes) != 3:
        raise ValueError("Digite exatamente três números (graus, minutos e segundos) separados por espaço.")

    g, m, s = map(float, partes)
    return abs(g) + (m / 60.0) + (s / 3600.0)

def formatar_dms(graus_decimais):
    """
    Recebe graus decimais e converte de volta para a string formatada G° M' S".
    Garante que os valores fiquem no intervalo 0-360°.
    """
    # Normaliza o ângulo para garantir que fique entre 0 e 360
    graus_decimais = graus_decimais % 360

    g = int(graus_decimais)
    resto_m = (graus_decimais - g) * 60
    m = int(resto_m)
    s = round((resto_m - m) * 60)

    # Tratamento de arredondamento (se o segundo arredondar para 60)
    if s >= 60:
        s = 0
        m += 1
    if m >= 60:
        m = 0
        g += 1

    g = g % 360
    return f"{g:02d}° {m:02d}' {s:02d}\""

# ==========================================
# FUNÇÕES DE INTERFACE (MENUS INDIVIDUAIS)
# ==========================================

def calcular_subtracao_360():
    print("\n--- 1. Subtrair ângulo de 360° ---")
    print("Exemplo de entrada: 12 56 34")
    entrada = input("Digite o ângulo: ")

    try:
        ang_dec = parse_angulo(entrada)
        resultado = 360.0 - ang_dec
        print(f"\n>> RESULTADO: {formatar_dms(resultado)}")
    except ValueError as e:
        print(f"\n[ERRO] {e}")
    except Exception:
        print("\n[ERRO] Ocorreu um problema. Certifique-se de digitar apenas números.")

def calcular_operacao_angulos():
    print("\n--- 2. Soma ou Subtração de Ângulos ---")
    ang1_str = input("Digite o 1º ângulo (ex: 45 10 00): ")
    ang2_str = input("Digite o 2º ângulo (ex: 10 30 15): ")
    operacao = input("Digite '+' para somar ou '-' para subtrair: ").strip()

    try:
        ang1 = parse_angulo(ang1_str)
        ang2 = parse_angulo(ang2_str)

        if operacao == '+':
            resultado = ang1 + ang2
        elif operacao == '-':
            resultado = ang1 - ang2
        else:
            print("\n[ERRO] Operação inválida. Use apenas '+' ou '-'.")
            return

        print(f"\n>> RESULTADO: {formatar_dms(resultado)}")
    except ValueError as e:
        print(f"\n[ERRO] {e}")
    except Exception:
        print("\n[ERRO] Entrada inválida. Verifique os dados inseridos.")

def calcular_coordenadas_relativas():
    print("\n--- 3. Calcular Coordenadas Relativas (X, Y) ---")
    azim_str = input("Digite o Azimute (ex: 12 56 34): ")
    # Aceita tanto vírgula quanto ponto e converte para float
    dist_str = input("Digite a Distância Horizontal: ").replace(',', '.')

    try:
        azim_dec = parse_angulo(azim_str)
        azim_rad = math.radians(azim_dec) # math do python exige radianos
        dist = float(dist_str)

        # Fórmulas topográficas clássicas
        x = dist * math.sin(azim_rad)
        y = dist * math.cos(azim_rad)

        print("\n>> RESULTADO:")
        print(f"Coord X (Eixo E/Leste) : {x:.3f} m")
        print(f"Coord Y (Eixo N/Norte) : {y:.3f} m")
    except ValueError as e:
        if "could not convert" in str(e).lower() or "não foi possível converter" in str(e).lower():
            print("\n[ERRO] A distância deve ser um número válido.")
        else:
            print(f"\n[ERRO] {e}")
    except Exception:
        print("\n[ERRO] Ocorreu um erro inesperado ao calcular as coordenadas.")

# ==========================================
# LOOP PRINCIPAL DO PROGRAMA
# ==========================================

def main():
    while True:
        print("\n=========================================")
        print("         CALCULADORA TOPOGRÁFICA         ")
        print("=========================================")
        print("1. Subtrair ângulo de 360°")
        print("2. Somar ou Subtrair dois ângulos")
        print("3. Calcular Coordenadas Relativas (XY)")
        print("0. Sair do programa")
        print("=========================================")

        escolha = input("Escolha uma opção: ").strip()

        if escolha == '1':
            calcular_subtracao_360()
        elif escolha == '2':
            calcular_operacao_angulos()
        elif escolha == '3':
            calcular_coordenadas_relativas()
        elif escolha == '0':
            print("\nEncerrando o script. Bom trabalho em campo!")
            break
        else:
            print("\n[AVISO] Opção inválida. Digite 1, 2, 3 ou 0.")

# Garante que o script rode apenas se executado diretamente
if __name__ == "__main__":
    main()